### question 1

In [26]:
a={'NAME':['siri','usha','jooo','deepika','sirisha'],'RollNO':[9,8,7,6,5],'place':['bvrm','nsp','elr','amp','pkl']}

In [27]:
import numpy as np
import pandas as pd

In [28]:
df=pd.DataFrame(a)

In [29]:
df

NAME  RollNO place
0     siri       9  bvrm
1     usha       8   nsp
2     jooo       7   elr
3  deepika       6   amp
4  sirisha       5   pkl

In [13]:
df.reindex([1,2,3,4,0])

NAME  RollNO place
1     usha       8   nsp
2     jooo       7   elr
3  deepika       6   amp
4  sirisha       5   pkl
0     siri       9  bvrm

### question 2

In [30]:
a=([2,4,6,8,10])

In [32]:
a1=pd.Series(a)

In [33]:
a1

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [34]:
b=([1,3,5,7,9])

In [35]:
b1=pd.Series(b)

In [36]:
b1

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [37]:
#### addition
a1+b1

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [38]:
######subtraction
a1-b1

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [39]:
##### multiplication
a1*b1

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [41]:
######division
a1/b1

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [42]:
###### modulous
a1%b1

0    0
1    1
2    1
3    1
4    1
dtype: int64

### question 3

In [43]:
a=([2,4,6,8,10])

In [44]:
a1=pd.Series(a)

In [45]:
a1

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [46]:
b=list(a1)

In [47]:
b

[2, 4, 6, 8, 10]

In [48]:
type(b)

list

### question 4

In [49]:
exam_data={'name':['Sachin','Ganguly','Kohli','Johnson','Taylor','Waugh','Yuvraj','Kambli','Srinath','Munaf'],'score':[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],'attempts':[1,3,2,3,2,3,1,1,2,1],'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}

In [50]:
a=pd.DataFrame(exam_data)

In [51]:
a

name  score  attempts qualify
0   Sachin   12.5         1     yes
1  Ganguly    9.0         3      no
2    Kohli   16.5         2     yes
3  Johnson    NaN         3      no
4   Taylor    9.0         2      no
5    Waugh   20.0         3     yes
6   Yuvraj   14.5         1     yes
7   Kambli    NaN         1      no
8  Srinath    8.0         2      no
9    Munaf   19.0         1     yes

In [55]:
a.isna().sum()

name        0
score       2
attempts    0
qualify     0
dtype: int64

### question 7

In [62]:
x = np.array(range(2,11))

In [60]:
x

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
y=x.reshape(3,3)
y

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

###  question 8

In [98]:
y=np.array([[1,2],[3,4],[5,6],[6,7]])
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [6, 7]])

In [99]:
np.ravel(y)

array([1, 2, 3, 4, 5, 6, 6, 7])

In [100]:
y.flatten()

array([1, 2, 3, 4, 5, 6, 6, 7])

### question 9

In [85]:
y

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [86]:
np.max(y)

10

In [87]:
np.min(y)

2

In [88]:
np.std(y)

2.581988897471611

In [89]:
np.cumsum(y)

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54], dtype=int32)

In [90]:
np.sum(y)

54

In [91]:
np.prod(y)

3628800

In [92]:
np.cumprod(y)

array([      2,       6,      24,     120,     720,    5040,   40320,
        362880, 3628800], dtype=int32)